name: CI for Jupyter Notebooks

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        pip install jupyter nbconvert pytest

    - name: Convert notebooks to scripts
      run: |
        jupyter nbconvert --to script getting_started.ipynb

    - name: Replace get_ipython Pip Installations
      run: |
        find notebooks -name "*.py" -exec sed -i -E 's/get_ipython\(\)\.run_line_magic\("pip", "install (.*)"\)/subprocess.check_call(["python", "-m", "pip", "install", "\1"])/g' {} +
    
    - name: Run tests
      env:
        OPENAI_API_KEY: ${{ secrets.AZURE_OPENAI_API_KEY }}
        AZURE_ENDPOINT: ${{ secrets.AZURE_OPENAI_API_ENDPOINT }}
      run: |
        pytest getting_started.py
    
    - name: Lint notebooks
      run: |
        flake8 getting_started.py
